sonar.projectKey=ChowRex_pylgb
sonar.projectName=pylgb
sonar.projectVersion=0.1.0

sonar.sources=src/pylgb
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.8
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=
  tests/**
  docs/**
